const Data = [
    { key: '1', description: "What is your favorite meal?" },
    { key: '2', description: "What sport are you good at?" },
    { key: '3', description: "If you were going to choose a new name for yourself, what would it be?" },
    { key: '4', description: "What is your favorite drink?" },
    { key: '5', description: "Tell me about your earliest memory." },
    { key: '6', description: "What is your mother like?" },
    { key: '7', description: "What is your dream job?" },
    { key: '8', description: "Do you have any pets?" },
    { key: '9', description: "Tell me about one of your bad habits." },
    { key: '10', description: "What is your favorite dessert?" },
    { key: '11', description: "What is your dream job?" },
    { key: '12', description: "Tell me about the best day you had last week." },
    { key: '13', description: "Can you speak any other languages?" },
    { key: '14', description: "What is your favorite TV show?" },
    { key: '15', description: "If you could live anywhere in the world, where would it be?" },
    { key: '16', description: "What are you most proud of achieving?" },
    { key: '17', description: "Tell me a funny story from your childhood. "},
    { key: '18', description: "Tell me about your favorite book." },
    { key: '19', description: "Who is your best friend? Can you tell me a story about them?" },
    { key: '20', description: "Do you obey rules you consider unfair?" },
    { key: '21', description: "What is your father like?" },
    { key: '22', description: "How do you order your pizza?" },
    { key: '23', description: "What is your favorite color?" },
    { key: '24', description: "Tell me about your earliest childhood memory." },
    { key: '25', description: "If you could have any superpower, what would it be?" },
    { key: '26', description: "What is your hometown like?" },
    { key: '27', description: "If you won 10 Million dollars, what is the first thing you would buy?" },
    { key: '28', description: "Tell me about your favorite vacation!" },
    { key: '29', description: "Who is your favorite cartoon character?" },
    { key: '30', description: "Do you play any instruments?" },
    { key: '31', description: "How do you react when someone disagrees with you?" },
    { key: '32', description: "Are you passionate about your culture?"  },
    { key: '33', description: "Do you have(or want to have) kids someday?" },
    { key: '34', description: "Describe your idea of a perfect day."},
    { key: '35', description: "Do you have a favorite genre of movies?" },
    { key: '36', description: "Do you have siblings? If so, what are they like?" },
    { key: '37', description: "What is your favorite holiday?" },
    { key: '38', description: "If you could add/change any law, what would it be?" },
    { key: '39', description: "What do you find yourself daydreaming about?" },
    { key: '40', description: "Tell me about what you are most grateful for." },
    { key: '41', description: "What do you value most in a friendship? " },
    { key: '42', description: "What is your preferred style of clothing?" },
    { key: '43', description: "Forest, mountains, desert, or beach?  " },
    { key: '44', description: "Tell me something embarrassing about yourself. " },
    { key: '45', description: "Do you have any hobbies?" },
    { key: '46', description: "What type of music do you like the most?" },
    { key: '47', description: "If you could spend an entire day with me, what would we do?" },
  ];

  export default Data;
